config/routes.rb
Rails.application.routes.draw do
  root to: 'orders#index'

  devise_for :users, controllers: { registrations: 'users' } do
    get 'sign_in', to: 'sessions#new', as: :new_user_session
  end
  

  get '/users/search', to: 'users#autocomplete'
  
  resources :users

  resources :orders
  resources :deliverymen
  resources :companies
  get '/users/finalize/:verification_code', to: 'users#finalize', as: 'finalize'
  patch 'finalize_save/:verification_code', to: 'users#finalize_save', as: 'finalize_save'
  post 'set_current_company', to: 'users#set_current_company'


  scope '/api' do
    scope '/v1' do
      #rotas de autenticação
      post 'authenticate', to: 'api/v1/authentication#authenticate' #autenticação
      
      #rota de criação de usuário
      post 'users', to: 'api/v1/users#create' #criar usuários

      #deliverymen routes
      post 'deliverymen/toggle_online', to: 'api/v1/deliverymen#toggle_online'
      get 'deliverymen/fetch_data', to: 'api/v1/deliverymen#fetch_data'

      #orders
      get 'orders', to: 'api/v1/orders#index'
      post 'orders/:id/accept', to: 'api/v1/orders#accept'
      put 'orders/:id/status', to: 'api/v1/orders#update_status'

    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  email_hash             :string
#  encrypted_password     :string           default(""), not null
#  is_online              :boolean
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  company_id             :bigint
#
# Indexes
#
#  index_users_on_company_id            (company_id)
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (company_id => companies.id)
#

class User < ApplicationRecord
  include Rails.application.routes.url_helpers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role: { company: 'company', admin: 'admin', deliveryman: 'deliveryman' }
  
  belongs_to :company

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile

  delegate :name, to: :profile, allow_nil: true

  accepts_nested_attributes_for :profile

  after_initialize :auto_fill_password
  after_initialize :setup_profile

  after_create :send_mail_to_finalize_register

  

  def configuration_last_year
    company.balance_sheets.where("year is not null").order(:year).configs.last.year
  end

  def last_significant_change
    Time.now + 6.years
  end 

  def setup_profile
  	self.profile ||= Profile.new
  end

  def auto_fill_password
    if !self.persisted?
      generated_password = Devise.friendly_token.first(8)         
      self.password ||= generated_password
      self.password_confirmation ||= generated_password  
    end
  end

  def send_mail_to_finalize_register
    self.email_hash =  SecureRandom.uuid
    self.save
    SetupUserMailer.with(user: self).setup.deliver_now
  end

  
  
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController
    skip_before_action :authenticate_request
    
    def create
        @user = Deliveryman.new(user_params)
        
        respond_to do |format|
            if @user.save
            format.html { redirect_to @user, notice: 'User was successfully created.' }
            format.json { render json: @user}
            else
            format.html { render :new }
            format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
        end

    private

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
        {
            "email"=>params[:email],  
            "name"=>params[:name],
            "cpf_cnpj"=>params[:cpf],
            "phone"=>params[:phone],
            "vehicle_model"=> params[:vehicle],
            "cep"=>params[:cep],
            "address"=>params[:address],
            "neighborhood"=>params[:district],
            "uf"=>params[:state],
            "city"=>params[:city],
            
        }
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:finalize, :finalize_save]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: :set_current_company

  def set_current_company
    @setted = current_user.set_current_company(params[:company_id])
    
    respond_to do |format|
      format.json{render json: @setted}
    end
  end
  

  # GET /users
  # GET /users.json
  def index
    @users = User.all.paginate(per_page: 10, page: params[:page])
  end

  def autocomplete
    @users = User.where("soundex(email) = soundex(?)", params[:query])

    respond_to do |format|
      format.json{render json: @users}
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def finalize
    cookies[:step] ||= 0
    @user = User.find_by_email_hash(params[:verification_code])
    respond_to do |format|
      format.html{render "finalize_step_#{cookies[:step].to_i + 1}"}  
    end
  end

  def finalize_save
    cookies[:step] ||= 0
    @user = User.find_by_email_hash(params[:verification_code])
    @user.update(finalize_user_params)
    if cookies[:step].to_i == 0
      has_error = @user.errors.any?
    elsif cookies[:step].to_i == 1
      has_error = @user.errors.any?
    end

    if has_error
      
    else
      cookies[:step] = cookies[:step].to_i + 1
    end

    respond_to do |format|
      if cookies[:step].to_i == 2
        cookies.delete(:step)
        
        flash[:notice] = 'Cadastro finalizado com sucesso'
        format.html{ redirect_to new_user_session_path }
      else
        format.html{render "finalize_step_#{cookies[:step] + 1}"}    
      end
      
    end

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def finalize_user_params
      params.require(:user).permit(:email, :password, :password_confirmation, profile_attributes: [:name, :cpf, :phone])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_scope, :email, profile_attributes: [:id, :name, :company_id, :role_id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
.bg-content
	= simple_form_for @user do |f|
		= f.input :user_scope, collection: User.user_scopes.map{|key, value| [I18n.t(key), key]}
		= f.simple_fields_for :profile do |p|
			=# = p.association :company
			=# = p.association :role
			= p.input :name
		= f.input :email
		
		= f.button :submit

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/finalize_step_1.haml
.bg-content.login

	.left
		.img
			= image_tag 'onboarding-icon.png'
		%h1 BEM VINDO AO SAGA
		%p Praesent ut felis pharetra, tempus velit non, lobortis tellus. Proin ut accumsan urna. 
	.right
		.inner
			.title
				Conclua seu cadastro para começar a utilizar a plataforma.
			.subtitle
				DEFINA SEUS DADOS DE ACESSO
			= simple_form_for @user, url: finalize_save_path(params[:verification_code]) do |f|
				= f.input :email
				= f.input :password
				= f.input :password_confirmation
				.actions
					= link_to "Forgot your password?", new_password_path(:user)
					%button Salvar
				

app/views/users/finalize_step_2.haml
.bg-content.login

	.left
		.img
			= image_tag 'onboarding-icon.png'
		%h1 BEM VINDO AO SAGA
		%p Praesent ut felis pharetra, tempus velit non, lobortis tellus. Proin ut accumsan urna. 
	.right
		.inner
			.title
				Conclua seu cadastro para começar a utilizar a plataforma.
			.subtitle
				DEFINA SEUS DADOS DE ACESSO
			= simple_form_for @user, url: finalize_save_path(params[:verification_code]) do |f|
				= f.simple_fields_for :profile do |p|
					= p.input :name
					= p.input :cpf
					= p.input :phone
				.actions
					= link_to "Forgot your password?", new_password_path(:user)
					%button Concluir
				

app/views/users/index.html.haml
.table-header
  %h1 Lista de usuários
  = link_to 'Adicionar novo', new_user_path, class: 'btn add right'
.flex
  .bg-content.width-100.margin-top-20
    %table
      %thead
        %tr
          %th Nome
          %th Perfil
          %th Email
          %th Empresa
          %th Status
          %th{colspan: 2} Ações
          

      %tbody
        - @users.each do |user|
          %tr
            %td=  user.name
            %td=  user.user_scope
            %td=  user.email
            %td=  user.company
            %td 
              .btn.active ativo
            %td= link_to 'editar', edit_user_path(user), class: 'btn edit'
            %td= link_to 'suspender', user, class: 'btn suspend'
    %hr
    = will_paginate @users
    %br

    

app/views/users/new.html.haml
%h1 Novo Usuário

= render 'form'

app/views/users/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path