config/routes.rb
Rails.application.routes.draw do
  root to: 'orders#index'

  devise_for :users, controllers: { registrations: 'users' } do
    get 'sign_in', to: 'sessions#new', as: :new_user_session
  end
  

  get '/users/search', to: 'users#autocomplete'
  
  resources :users

  resources :orders
  resources :deliverymen
  resources :companies
  get '/users/finalize/:verification_code', to: 'users#finalize', as: 'finalize'
  patch 'finalize_save/:verification_code', to: 'users#finalize_save', as: 'finalize_save'
  post 'set_current_company', to: 'users#set_current_company'


  scope '/api' do
    scope '/v1' do
      #rotas de autenticação
      post 'authenticate', to: 'api/v1/authentication#authenticate' #autenticação
      
      #rota de criação de usuário
      post 'users', to: 'api/v1/users#create' #criar usuários

      #deliverymen routes
      post 'deliverymen/toggle_online', to: 'api/v1/deliverymen#toggle_online'
      get 'deliverymen/fetch_data', to: 'api/v1/deliverymen#fetch_data'

      #orders
      get 'orders', to: 'api/v1/orders#index'
      post 'orders/:id/accept', to: 'api/v1/orders#accept'
      put 'orders/:id/status', to: 'api/v1/orders#update_status'

    end
  end
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id                       :bigint           not null, primary key
#  destination_accountable  :string
#  destination_address      :string
#  destination_city         :string
#  destination_neighborhood :string
#  destination_phone        :string
#  destination_state        :string
#  note                     :string
#  state                    :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  company_id               :bigint
#  deliveryman_id           :bigint
#
# Indexes
#
#  index_orders_on_company_id      (company_id)
#  index_orders_on_deliveryman_id  (deliveryman_id)
#
# Foreign Keys
#
#  fk_rails_...  (company_id => companies.id)
#  fk_rails_...  (deliveryman_id => deliverymen.id)
#

class Order < ApplicationRecord
  belongs_to :deliveryman
  belongs_to :company
  before_create :setup_first_state
  before_update :avoid_empty_state
  after_create :send_notification
  enum state: {
  	pending: 'pending',
  	on_way: 'on_way',
	picking_up: "picking_up",
	back_to_company: 'back_to_company',
  	completed: 'completed',
  	canceled: 'canceled'
  }

  def avoid_empty_state
  	if state == nil
  		state = state_was
  	end
  end

  def send_notification
	data = {
		notification_type: "new_order",
		order: OrderSerializer.new(self).serializable_hash
	}
	
	
	buttons = OneSignal::Buttons.new(
		buttons: [{id: 'accept', text: 'Aceitar' }, {id: 'reject', text: 'Rejeitar' }]
	)
	Deliveryman.send_notification("Pedido", "Existe um novo pedido disponível", data, buttons)
  end

  def test_deliver
	self.state = "pending"
	self.save
	self.send_notification
  end

  def possible_states
  	case state
  	when 'pending'
  		['on_way', 'canceled']
	when 'on_way'
		['completed', 'canceled']
	else
		[]
  	end
  end

  def delivery_update
	case state
	when "picking_up"
		self.state = "on_way"
	when 'on_way'
		self.state = "back_to_company"
	when 'back_to_company'
		self.state = "completed"
	else
		raise "Não é possível alterar outros estados"
	end

	self.save
  end

  def deliveryman_action_text
	case state
	when "picking_up"
		"Peguei o pedido"
	when 'on_way'
		"Realizei a entrega"
	when 'back_to_company'
		"Retornou ao estabelecimento"
	when "completed"
		"Concluido"
	end
  end

  def set_deliveryman(deliveryman)
	self.deliveryman_id = deliveryman.id
	self.state = 'picking_up'
	self.save
  end

  def setup_first_state
  	self.state = 'pending'
  end

  def is_delivered?
	!["pending", "canceled", "picking_up", "on_way"].include?(self.state)
  end

  def is_picked?
	!["pending", "canceled", "picking_up"].include?(self.state)
  end
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < Api::V1::ApplicationController
    before_action :set_deliveryman

    def accept
        
        order = Order.pending.find(params[:id])
        order.set_deliveryman(@deliveryman)

        respond_to do |format|
            format.json{render json: OrderSerializer.new(order).serializable_hash.to_json}
        end
    end

    def update_status
        
        order = Order.find(params[:id])
        order.delivery_update

        respond_to do |format|
            format.json{render json: OrderSerializer.new(order).serializable_hash.to_json}
        end
    end

    def index
        orders = @deliveryman.orders

        respond_to do |format|
            format.json{render json: OrderSerializer.new(orders).serializable_hash.to_json}
        end
    end

    private
    def set_deliveryman
        @deliveryman = current_user
    end
   
end 

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /orders
  # GET /orders.json
  def index
    
    if current_user.company?
      @orders = current_user.company.orders
    elsif current_user.admin?
      @orders = Order.all  
    end
    @deliverymen = Deliveryman.order(:name)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    if current_user.admin?
      @order = Order.new(order_params)
    elsif current_user.company?
      @order = current_user.company.orders.new(order_params)
    end
    

    respond_to do |format|
      if @order.save
        format.html { redirect_to orders_path, notice: 'O pedido foi criado com sucesso' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:destination_accountable, :destination_address, :destination_city, :destination_neighborhood, :destination_state, :destination_phone, :note, :company_id, :deliveryman_id, :state)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
-# frozen_string_literal: true
.width-100.balance_sheets
  .flex
    .bg-content
      = simple_form_for(@order) do |f|
        = f.error_notification
        = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

        .form-inputs
          = f.input :destination_accountable
          = f.input :destination_address
          = f.input :destination_city, input_html: {value: current_user.company.city}
          = f.input :destination_neighborhood
          = f.input :destination_phone
          = f.input :destination_state, input_html: {value: current_user.company.state}
          = f.input :note
          -if current_user.admin?
            = f.association :company
            = f.association :deliveryman

        .form-actions
          = f.button :submit

app/views/orders/edit.html.haml
%h1 Editing order

= render 'form'

= link_to 'Show', @order
\|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
.table-header
  %h1 Pedidos
  = link_to fa_icon('refresh'), orders_path, class: 'btn refresh right'
  - if current_user.company?
    = link_to 'Adicionar novo', new_order_path, class: 'btn add right'
.flex.margin-top-20
  .bg-content.width-100
    %table.bordered
      %thead
        %tr
          %th= Order.human_attribute_name(:destination_accountable)
          %th= Order.human_attribute_name(:destination_address)
          %th= Order.human_attribute_name(:destination_phone)
          %th= Order.human_attribute_name(:note)
          %th= Order.human_attribute_name(:company)
          %th= Order.human_attribute_name(:deliveryman)
          -if current_user.admin?
            %th
          %th Status

      %tbody
        - @orders.each do |order|
          %tr
            %td= order.destination_accountable
            %td= order.destination_address
            %td= order.destination_phone
            %td= order.note
            %td= order.company
            %td= order.deliveryman
            -if current_user.admin?
              %td= react_component 'EditOrder', {order: order, possible_states: order.possible_states, deliverymen: @deliverymen}
            %td
              %label{class: "#{order.state}-state"}
                = I18n.t(order.state)

    %br

app/views/orders/new.html.haml
%h1 Novo pedido

= render 'form'

app/views/orders/show.html.haml
%p#notice= notice

%p
  %b Destination accountable:
  = @order.destination_accountable
%p
  %b Destination address:
  = @order.destination_address
%p
  %b Destination phone:
  = @order.destination_phone
%p
  %b Note:
  = @order.note
%p
  %b Company:
  = @order.company_id
%p
  %b Deliveryman:
  = @order.deliveryman_id

= link_to 'Edit', edit_order_path(@order)
\|
= link_to 'Back', orders_path