config/routes.rb
Rails.application.routes.draw do
  root to: 'orders#index'

  devise_for :users, controllers: { registrations: 'users' } do
    get 'sign_in', to: 'sessions#new', as: :new_user_session
  end
  

  get '/users/search', to: 'users#autocomplete'
  
  resources :users

  resources :orders
  resources :deliverymen
  resources :companies
  get '/users/finalize/:verification_code', to: 'users#finalize', as: 'finalize'
  patch 'finalize_save/:verification_code', to: 'users#finalize_save', as: 'finalize_save'
  post 'set_current_company', to: 'users#set_current_company'


  scope '/api' do
    scope '/v1' do
      #rotas de autenticação
      post 'authenticate', to: 'api/v1/authentication#authenticate' #autenticação
      
      #rota de criação de usuário
      post 'users', to: 'api/v1/users#create' #criar usuários

      #deliverymen routes
      post 'deliverymen/toggle_online', to: 'api/v1/deliverymen#toggle_online'
      get 'deliverymen/fetch_data', to: 'api/v1/deliverymen#fetch_data'

      #orders
      get 'orders', to: 'api/v1/orders#index'
      post 'orders/:id/accept', to: 'api/v1/orders#accept'
      put 'orders/:id/status', to: 'api/v1/orders#update_status'

    end
  end
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id           :bigint           not null, primary key
#  accountable  :string
#  address      :string
#  city         :string
#  cpf_cnpj     :string
#  email        :string
#  name         :string
#  neighborhood :string
#  phone        :string
#  state        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Company < ApplicationRecord
	after_create :setup_user
	has_many :orders

	def setup_user
		User.create(email: self.email, role: :company, company_id: self.id)
	end

	def to_s
		"#{name}"
	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :check_role

  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def check_role
    if !current_user.admin?
      redirect_to :orders, alert: "Você não tem permissão pra acessar essa área"
    end
  end
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to companies_path, notice: 'Empresa criada com sucesso' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:accountable, :address, :city, :cpf_cnpj, :email, :name, :neighborhood, :phone, :state)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.haml
-# frozen_string_literal: true
.width-100.balance_sheets
  .flex
    .bg-content
      = simple_form_for(@company) do |f|
        = f.error_notification
        = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

        .form-inputs
          = f.input :accountable
          = f.input :address
          = f.input :city
          = f.input :cpf_cnpj
          = f.input :email
          = f.input :name
          = f.input :neighborhood
          = f.input :phone
          = f.input :state

        .form-actions
          = f.button :submit

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

app/views/companies/index.html.haml
.table-header
  %h1 Empresas
  = link_to 'Adicionar novo', new_company_path, class: 'btn add right'
.flex.margin-top-20
  .bg-content.width-100
    %table.bordered
      %thead
        %tr
          %th= Company.human_attribute_name(:accountable)
          %th= Company.human_attribute_name(:address)
          %th= Company.human_attribute_name(:city)
          %th= Company.human_attribute_name(:cpf_cnpj)
          %th= Company.human_attribute_name(:email)
          %th= Company.human_attribute_name(:name)
          %th= Company.human_attribute_name(:neighborhood)
          %th= Company.human_attribute_name(:phone)
          %th= Company.human_attribute_name(:state)
          %th
          %th
          

      %tbody
        - @companies.each do |company|
          %tr
            %td= company.accountable
            %td= company.address
            %td= company.city
            %td= company.cpf_cnpj
            %td= company.email
            %td= company.name
            %td= company.neighborhood
            %td= company.phone
            %td= company.state
            %td= link_to 'Editar', edit_company_path(company)
            %td= link_to 'Deletar', company, method: :delete, data: { confirm: 'Você tem certeza?' }

    %br

app/views/companies/new.html.haml
%h1 Nova empresa

= render 'form'

app/views/companies/show.html.haml
%p#notice= notice

%p
  %b Accountable:
  = @company.accountable
%p
  %b Address:
  = @company.address
%p
  %b City:
  = @company.city
%p
  %b Cpf cnpj:
  = @company.cpf_cnpj
%p
  %b Email:
  = @company.email
%p
  %b Name:
  = @company.name
%p
  %b Neighborhood:
  = @company.neighborhood
%p
  %b Phone:
  = @company.phone
%p
  %b State:
  = @company.state

= link_to 'Edit', edit_company_path(@company)
\|
= link_to 'Back', companies_path